import type { Metadata } from "next";
import Link from "next/link";
import { Manrope } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Contact from "@/app/media/_components/sections/Contact";
import AboutEffects from "./_components/AboutEffects";
import TrustCarousel from "./_components/TrustCarousel";
import "./about.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: { absolute: "About Markition | AI, Marketing, Technology & Design Growth Partner" },
  description:
    "Discover Markition — an integrated growth partner combining AI, digital marketing, technology and design.",
  alternates: { canonical: "https://markition.com/about" },
  openGraph: {
    title: "About Markition | AI, Marketing, Technology & Design Growth Partner",
    description:
      "Discover Markition — an integrated growth partner combining AI, digital marketing, technology and design.",
    url: "https://markition.com/about",
    siteName: "Markition",
  },
};

export default function AboutPage() {
  return (
    <div style={{ background: "#05060d" }}>
      <Navbar />
      <AboutEffects />

      <main className={`about-page ${manrope.variable}`}>
        <section className="hero"><div className="wrap"><div className="eyebrow reveal">About Markition / The Growth Ecosystem</div><h1><span className="reveal">WE DON&apos;T JUST</span><span className="reveal">BUILD <i className="blue">DIGITAL.</i></span><span className="reveal">WE BUILD WHAT</span><span className="reveal">MOVES BUSINESS</span><span className="reveal">FORWARD.</span></h1><div className="hero-bottom reveal"><p className="hero-copy">Marketing. Technology. Design. AI.<br /><b>One connected growth ecosystem.</b></p><div className="actions"><a className="btn primary" href="#about">Meet Markition →</a><a className="btn ghost" href="#pillars">Explore What We Build</a></div></div></div></section>
        <section className="section idea" id="about"><div className="wrap grid2"><div><div className="eyebrow reveal">01 / The Idea</div><div className="idea question reveal">WHAT IF YOUR BUSINESS DIDN&apos;T NEED FIVE DIFFERENT PARTNERS?</div></div><div className="answer reveal">Marketing from one team.<br />Technology from another.<br />Design somewhere else.<br />AI as another conversation.<br /><br />Different teams. Different strategies. Different priorities.<strong>WE BUILT A DIFFERENT MODEL.<br /><span style={{ color: "#0018c5" }}>ONE TEAM.<br />ONE STRATEGY.<br />ONE GROWTH ECOSYSTEM.</span></strong></div></div></section>
        <section className="section ecosystem" id="ecosystem"><div className="wrap grid2"><div className="reveal"><div className="eyebrow">02 / The Connection</div><h2 className="title">MARKITION <span className="blue">CONNECTS</span> THE PIECES.</h2><p className="lead" style={{ color: "#bcc4dd" }}>Media brings demand. Tech builds infrastructure. Design creates perception. AI creates intelligence. Markition connects everything.</p></div><div className="orbit reveal"><div className="center">MARKITION</div><div className="node a">MEDIA</div><div className="node b">TECH</div><div className="node c">DESIGN LAB</div><div className="node d">SPHENO AI</div></div></div></section>
        <section className="section pillars" id="pillars"><div className="wrap"><div className="grid2" style={{ marginBottom: "65px" }}><div><div className="eyebrow reveal">03 / One Ecosystem</div><h2 className="title reveal">EVERY PIECE<br /><span className="blue">WORKS TOGETHER.</span></h2></div><p className="lead reveal">Five connected capabilities. One shared strategy. A single partner built to move the business forward.</p></div>
        <article className="pillar reveal"><div className="media"><img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=80" alt="Performance marketing data" loading="lazy" /></div><div className="copy"><div className="chapter">Chapter 01 / Media</div><h2>MEDIA</h2><h3>Turn attention into opportunity.</h3><div className="tags"><span>Google Ads</span><span>Meta Ads</span><span>Social Media</span><span>SEO</span><span>GEO</span><span>AEO</span><span>Content</span><span>Lead Generation</span></div><Link className="link" href="/media">Explore Media →</Link></div></article>
        <article className="pillar reveal"><div className="media"><img src="https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=80" alt="Software architecture" loading="lazy" /></div><div className="copy"><div className="chapter">Chapter 02 / Markition Tech</div><h2>MARKITION<br />TECH</h2><h3>Build the infrastructure behind growth.</h3><div className="tags"><span>Web</span><span>Mobile Apps</span><span>SaaS</span><span>PaaS</span><span>ERP</span><span>CRM</span><span>E-Commerce</span><span>Custom Software</span></div><Link className="link" href="/tech">Explore Tech →</Link></div></article>
        <article className="pillar reveal"><div className="media"><img src="https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1400&q=80" alt="Brand and design work" loading="lazy" /></div><div className="copy"><div className="chapter">Chapter 03 / Design Lab</div><h2>DESIGN<br />LAB</h2><h3>Make the business impossible to ignore.</h3><div className="tags"><span>Branding</span><span>Visual Identity</span><span>UI/UX</span><span>Graphic Design</span><span>Motion</span><span>2D/3D</span><span>Creative</span><span>Pitch Decks</span></div><Link className="link" href="/design-lab">Explore Design Lab →</Link></div></article>
        <article className="pillar reveal"><div className="media"><img src="https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=80" alt="Artificial intelligence interface" loading="lazy" /></div><div className="copy"><div className="chapter">Chapter 04 / SPHENO AI</div><h2>SPHENO<br />AI</h2><h3>Make the business intelligent.</h3><div className="tags"><span>AI Agents</span><span>AI Chatbots</span><span>Voice AI</span><span>Workflow Automation</span><span>CRM Automation</span><span>WhatsApp AI</span><span>Assistants</span></div><Link className="link" href="/spheno">Explore SPHENO AI →</Link></div></article></div></section>
        <section className="section soft"><div className="wrap who"><div><div className="eyebrow reveal">04 / Who We Are</div><h2 className="big reveal">WE&apos;RE NOT HERE TO JUST <span>DELIVER PROJECTS.</span></h2></div><p className="lead reveal" style={{ fontSize: "17px" }}>We&apos;re here to move businesses forward.<br /><br />Markition brings strategy, marketing, technology, design and AI together under one growth ecosystem. We work with businesses that want more than isolated services. They want a partner who understands where they are going — and knows how to help them get there.</p></div></section>
        <section className="section timeline"><div className="wrap"><div className="grid2"><div><div className="eyebrow reveal">05 / The Story</div><h2 className="title reveal">HOW IT<br /><span className="blue">STARTED.</span></h2></div><p className="lead reveal" style={{ color: "#aab2c8" }}>From a simple belief in connecting creativity and technology to an integrated digital growth ecosystem.</p></div><div className="timelinegrid"><div className="time reveal"><div className="year">2023</div><h4>The Beginning</h4><p>Markition was founded with a vision to bridge the gap between creativity and technology.</p></div><div className="time reveal"><div className="year">01</div><h4>Expansion</h4><p>Capabilities expanded across marketing, software development, SEO and design.</p></div><div className="time reveal"><div className="year">02</div><h4>The Ecosystem</h4><p>Media, Markition Tech, Design Lab and SPHENO AI became connected parts of one model.</p></div><div className="time reveal"><div className="year">NOW</div><h4>One Growth Partner</h4><p>An integrated digital growth partner built around strategy, execution and intelligent systems.</p></div></div></div></section>
        <section className="founder"><div className="founderimg"><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1400&q=80" alt="Leadership and strategy environment" loading="lazy" /></div><div className="foundercopy"><div className="eyebrow">06 / Founder</div><h2 className="reveal">BUILT WITH A SIMPLE BELIEF.</h2><div className="name">SHAHRUKH KHAN / CEO &amp; DIRECTOR, MARKITION</div><p className="reveal">Markition is built around the idea that creativity and technology should not operate in separate worlds. The company’s direction is focused on building an integrated team and long-term growth partner — connecting strategy, creative thinking, technology and intelligent systems around real business goals.</p></div></section>
        <section className="section belief"><div className="wrap"><div className="eyebrow">07 / Our Belief</div><h2 className="reveal">GROWTH DOESN&apos;T HAPPEN <span>IN SILOS.</span></h2><p className="reveal">Marketing without technology has limits. Technology without design gets ignored. Design without strategy loses direction. AI without purpose becomes noise.<br /><br /><b style={{ color: "#fff" }}>THE BEST RESULTS HAPPEN WHEN EVERYTHING WORKS TOGETHER.</b></p></div></section>
        <section className="section"><div className="wrap approach"><div><div className="eyebrow reveal">08 / How We Work</div><h2 className="title reveal">FROM IDEA<br /><span className="blue">TO IMPACT.</span></h2></div><div className="list"><div className="item reveal"><b>01</b><div><h4>DISCOVER</h4><p>Understand the business, audience and opportunity.</p></div></div><div className="item reveal"><b>02</b><div><h4>DEFINE</h4><p>Build the strategy around the business problem.</p></div></div><div className="item reveal"><b>03</b><div><h4>CREATE</h4><p>Design, develop and execute with purpose.</p></div></div><div className="item reveal"><b>04</b><div><h4>OPTIMIZE</h4><p>Measure, learn and improve what matters.</p></div></div><div className="item reveal"><b>∞</b><div><h4>REPEAT</h4><p>Growth is a system — not a one-time deliverable.</p></div></div></div></div></section>
        <section className="section global" id="global"><div className="wrap grid2"><div><div className="eyebrow reveal">09 / Global Reach</div><h2 className="title reveal">BUILT HERE.<br /><span className="blue">BUILT FOR<br />THE WORLD.</span></h2><p className="lead reveal" style={{ color: "#bac2d9" }}>Pakistan, Saudi Arabia, United States, UAE and United Kingdom are key markets in Markition&apos;s ecosystem — businesses we work with, wherever they are.</p></div><div className="map reveal"><span className="pin p1">United States</span><span className="pin p2">United Kingdom</span><span className="pin p3">Pakistan</span><span className="pin p4">Saudi Arabia</span><span className="pin p5">UAE</span></div></div></section>
        <section className="section work" id="work"><div className="wrap"><div className="grid2" style={{ marginBottom: "60px" }}><div><div className="eyebrow reveal">10 / The Work</div><h2 className="title reveal">WE LET THE<br /><span className="blue">WORK TALK.</span></h2></div><p className="lead reveal">Work across AI solutions, web platforms, mobile apps, digital marketing and brand experiences.</p></div><div className="workgrid"><Link className="workcard big reveal" href="/#portfolio"><img src="https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=80" alt="AI solutions" loading="lazy" /><div className="wi"><small>AI Solutions</small><h3>Intelligent Systems</h3><p>Explore the Markition portfolio →</p></div></Link><Link className="workcard reveal" href="/#portfolio"><img src="https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1400&q=80" alt="Brand experience" loading="lazy" /><div className="wi"><small>Brand Experiences</small><h3>Digital Craft</h3><p>View portfolio →</p></div></Link></div></div></section>

        <TrustCarousel />

        <section className="future"><div className="wrap"><div className="eyebrow">12 / The Future</div><h2>THE FUTURE OF BUSINESS<br />ISN&apos;T JUST DIGITAL.<span>IT&apos;S INTELLIGENT.</span></h2><p>AI + Marketing + Technology + Design. One connected future.</p></div></section>
        <section className="section spheno"><div className="wrap grid2"><div><div className="eyebrow">13 / SPHENO AI</div><h2 className="title">AND THIS IS WHERE <span className="blue">SPHENO COMES IN.</span></h2><p className="lead" style={{ color: "#aeb6d0" }}>AI shouldn&apos;t just answer questions. It should move work forward.</p><Link className="btn primary" href="/spheno">Explore SPHENO AI →</Link></div><div className="flow"><div className="flowrow"><span>01</span>LEAD ARRIVES</div><div className="flowrow"><span>02</span>AI UNDERSTANDS</div><div className="flowrow"><span>03</span>AI SCORES</div><div className="flowrow"><span>04</span>AI RESPONDS</div><div className="flowrow"><span>05</span>AI SCHEDULES</div><div className="flowrow"><span>06</span>TEAM TAKES OVER</div></div></div></section>
        <section className="section final"><div className="wrap"><div className="eyebrow">14 / The Statement</div><h2>MARKITION<br /><span>WE BUILD<br />WHAT&apos;S NEXT.</span></h2><p className="lead" style={{ margin: "30px auto" }}>Marketing. Technology. Design. AI.<br /><b>One growth ecosystem.</b></p><div className="actions" style={{ justifyContent: "center" }}><a className="btn primary" href="#contact">Build With Markition →</a><a className="btn" style={{ color: "#080c42", borderColor: "#d7dce6" }} href="#pillars">Explore Our Solutions</a></div></div></section>
        <section className="cta" id="cta"><h2>YOUR NEXT CHAPTER<br />STARTS HERE.</h2><p>Whether you need more leads, a stronger digital product, a sharper brand or intelligent automation — let&apos;s build what moves your business forward.</p><div className="actions" style={{ justifyContent: "center" }}><a className="btn primary" style={{ background: "#fff", color: "#080c42", borderColor: "#fff" }} href="#contact">Book A Free Consultation →</a><a className="btn ghost" href="mailto:hey@markition.com">Talk To Our Team</a></div></section>
      </main>

      {/* Call booking — same form used across the Markition solution pages */}
      <div style={{ background: "#020a1c" }}>
        <Contact />
      </div>

      <Footer />
    </div>
  );
}
